name: Add ignore status label

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

jobs:
  add-ignore-label:
    if: github.head_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Add ignore status label
        uses: actions/github-script@v6.1.0
        env:
          TZ: Asia/Tokyo
        with:
          script: |
            github.rest.issues.addLabels({
              ...context.repo,
              issue_number: context.issue.number,
              labels: ["ignore-stats"]
            })