name: Add ignore status label

on:
  pull_request:
    types: [opened]
    branches:
      - develop

jobs:
  add-ignore-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add ignore status label
        uses: actions/github-script@v6.1.0
        env:
          TZ: Asia/Tokyo
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              ...context.repo,
              issue_number: pr.number,
              labels: ["ignore-stats"]
            })
