name: Add ignore status label

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

jobs:
  add-ignore-label:
    if: github.head_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              ...context.repo,
              labels: ["ignore-stats"]
            });