name: Add ignore status label

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  add-ignore-label22:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello"
      - name: Add ignore status label
        if: >-
          github.event.pull_request.merged == true &&
          github.head_ref == 'develop'
        uses: actions/github-script@v7
        env:
          TZ: Asia/Tokyo
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["ignore-stats"]
            })