name: Create Pull Request for master when merged directly into release

on:
  pull_request:
    types: [closed]
    branches: ['main']

jobs:
  create-pr:
    if: >-
      github.event.pull_request.merged == true &&
      github.head_ref != 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check PullRequest Exists
        id: check_pr
        env:
            HEAD_MESSAGE: ${{ github.event.pull_request.head.sha }}
        run: |
          COMMIT_MESSAGE=$(echo "${HEAD_MESSAGE}" | sed -n -e 1p)
          echo "message=${COMMIT_MESSAGE}" >> "$GITHUB_OUTPUT"
          echo "count=$(gh pr list -B main -H develop -S | wc -l)" >> "$GITHUB_OUTPUT"
      - name: test
        run: |
          echo "count=${{ steps.check_pr.outputs.count }}"
      - name: Create Release Pull Request
        if: ${{ steps.check_pr.outputs.count == 0 }}
        run: |
          gh pr create \
            -B develop \
            -t '【Release → Master】masterブランチの最新化' \
            -a ${{ github.actor }}  \
            --body "release → master "